# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlacesSearch
                                 A QGIS plugin
 Fetch places data from Google Maps API and save to Shapefile.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-02
        copyright            : (C) 2025 by Yanni Wang
        email                : yanni.wang2000@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlacesSearch class from file PlacesSearch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .places_search import PlacesSearch
    return PlacesSearch(iface)
