# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'places_search_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlacesSearchDialogBase(object):
    def setupUi(self, PlacesSearchDialogBase):
        PlacesSearchDialogBase.setObjectName("PlacesSearchDialogBase")
        PlacesSearchDialogBase.resize(500, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlacesSearchDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.api_key_label = QtWidgets.QLabel(PlacesSearchDialogBase)
        self.api_key_label.setObjectName("api_key_label")
        self.verticalLayout.addWidget(self.api_key_label)
        self.api_key_input = QtWidgets.QLineEdit(PlacesSearchDialogBase)
        self.api_key_input.setObjectName("api_key_input")
        self.verticalLayout.addWidget(self.api_key_input)
        self.keyword_label = QtWidgets.QLabel(PlacesSearchDialogBase)
        self.keyword_label.setObjectName("keyword_label")
        self.verticalLayout.addWidget(self.keyword_label)
        self.keyword_input = QtWidgets.QLineEdit(PlacesSearchDialogBase)
        self.keyword_input.setObjectName("keyword_input")
        self.verticalLayout.addWidget(self.keyword_input)
        self.polygon_label = QtWidgets.QLabel(PlacesSearchDialogBase)
        self.polygon_label.setObjectName("polygon_label")
        self.verticalLayout.addWidget(self.polygon_label)
        self.polygon_layer_combo = QtWidgets.QComboBox(PlacesSearchDialogBase)
        self.polygon_layer_combo.setObjectName("polygon_layer_combo")
        self.verticalLayout.addWidget(self.polygon_layer_combo)
        self.output_path_label = QtWidgets.QLabel(PlacesSearchDialogBase)
        self.output_path_label.setObjectName("output_path_label")
        self.verticalLayout.addWidget(self.output_path_label)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.output_path_input = QtWidgets.QLineEdit(PlacesSearchDialogBase)
        self.output_path_input.setObjectName("output_path_input")
        self.hboxlayout.addWidget(self.output_path_input)
        self.browse_button = QtWidgets.QPushButton(PlacesSearchDialogBase)
        self.browse_button.setObjectName("browse_button")
        self.hboxlayout.addWidget(self.browse_button)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.search_button = QtWidgets.QPushButton(PlacesSearchDialogBase)
        self.search_button.setObjectName("search_button")
        self.verticalLayout.addWidget(self.search_button)

        self.retranslateUi(PlacesSearchDialogBase)
        QtCore.QMetaObject.connectSlotsByName(PlacesSearchDialogBase)

    def retranslateUi(self, PlacesSearchDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PlacesSearchDialogBase.setWindowTitle(_translate("PlacesSearchDialogBase", "Google Places Search"))
        self.api_key_label.setText(_translate("PlacesSearchDialogBase", "Google API Key:"))
        self.api_key_input.setPlaceholderText(_translate("PlacesSearchDialogBase", "Enter your API key"))
        self.keyword_label.setText(_translate("PlacesSearchDialogBase", "Search Keywords:"))
        self.keyword_input.setPlaceholderText(_translate("PlacesSearchDialogBase", "e.g., Aged Care Service, Nursing Home"))
        self.polygon_label.setText(_translate("PlacesSearchDialogBase", "Select Polygon:"))
        self.output_path_label.setText(_translate("PlacesSearchDialogBase", "Output Path:"))
        self.output_path_input.setPlaceholderText(_translate("PlacesSearchDialogBase", "Select output path..."))
        self.browse_button.setText(_translate("PlacesSearchDialogBase", "Browse"))
        self.search_button.setText(_translate("PlacesSearchDialogBase", "Run Search"))
